# Generated by Django 5.2.11 on 2026-02-23 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='kanban.board'),
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.board'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kanban.boardcolumn'),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='kanban.board'),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.boardcolumn'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kanban.card'),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.card'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kanban.cardcomment'),
        ),
        migrations.AddField(
            model_name='cardlabel',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='kanban.card'),
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='kanban.board'),
        ),
        migrations.AddField(
            model_name='cardlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_cards', to='kanban.label'),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='cards', through='kanban.CardLabel', to='kanban.label'),
        ),
        migrations.AddIndex(
            model_name='boardcolumn',
            index=models.Index(fields=['board', 'position'], name='kanban_boar_board_i_4451eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardmembership',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='uniq_board_user_membership'),
        ),
        migrations.AddIndex(
            model_name='cardcomment',
            index=models.Index(fields=['card', 'created_at'], name='kanban_card_card_id_5eb701_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['board', 'created_at'], name='kanban_acti_board_i_0fd031_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor_user'], name='kanban_acti_actor_u_85567f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='kanban_acti_action_407f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_label_name_per_board'),
        ),
        migrations.AddConstraint(
            model_name='cardlabel',
            constraint=models.UniqueConstraint(fields=('card', 'label'), name='uniq_card_label'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['column', 'position'], name='kanban_card_column__f189d9_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['priority'], name='kanban_card_priorit_64fd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['due_at'], name='kanban_card_due_at_f4ae8e_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['assignee'], name='kanban_card_assigne_fd53a9_idx'),
        ),
    ]
